# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 2
  database: store_app_db
  host: 127.0.0.1
  username: wangxiaoshuai
  password: 123123
